window.env = {
  "ACLOCAL_PATH": "C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "AMDRMSDKPATH": "C:\\Program Files\\AMD\\RyzenMasterSDK\\",
  "API_KEY": "0cd40f3197f94ea2ad6165103233008",
  "APPDATA": "C:\\Users\\siddh\\AppData\\Roaming",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "133164515079485841",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_4500_WTUTDSGHJFVUZKQK",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "MERO_PC",
  "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
  "CONFIG_SITE": "C:/Program Files/Git/etc/config.site",
  "DISPLAY": "needs-to-be-defined",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "EFC_7592": "1",
  "EXEPATH": "C:\\Program Files\\Git\\bin",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\siddh\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\siddh",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\siddh",
  "HOSTNAME": "Mero_pc",
  "INFOPATH": "C:\\Program Files\\Git\\mingw64\\local\\info;C:\\Program Files\\Git\\mingw64\\share\\info;C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info",
  "INIT_CWD": "D:\\Reactprojects\\Weather\\client",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\siddh\\AppData\\Local",
  "LOGONSERVER": "\\\\MERO_PC",
  "MANPATH": "C:\\Program Files\\Git\\mingw64\\local\\man;C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man",
  "MINGW_CHOST": "x86_64-w64-mingw32",
  "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
  "MINGW_PREFIX": "C:/Program Files/Git/mingw64",
  "MSYSTEM": "MINGW64",
  "MSYSTEM_CARCH": "x86_64",
  "MSYSTEM_CHOST": "x86_64-w64-mingw32",
  "MSYSTEM_PREFIX": "C:/Program Files/Git/mingw64",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\siddh\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\siddh\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\siddh\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\siddh\\.npm-init.js",
  "npm_config_local_prefix": "D:\\Reactprojects\\Weather\\client",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\siddh\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\siddh\\.npmrc",
  "npm_config_user_agent": "npm/8.19.2 node/v18.12.1 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "D:\\Reactprojects\\Weather\\client\\package.json",
  "npm_package_name": "client",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\siddh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OLDPWD": "D:/Reactprojects/Weather",
  "OneDrive": "C:\\Users\\siddh\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\siddh\\OneDrive",
  "OnlineServices": "Online Services",
  "ORIGINAL_PATH": "C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\siddh\\bin;C:\\Python311\\Scripts;C:\\Python311;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\siddh\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\siddh\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\siddh\\AppData\\Roaming\\npm",
  "ORIGINAL_TEMP": "C:/Users/siddh/AppData/Local/Temp",
  "ORIGINAL_TMP": "C:/Users/siddh/AppData/Local/Temp",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "PATH": "D:\\Reactprojects\\Weather\\client\\node_modules\\.bin;D:\\Reactprojects\\Weather\\node_modules\\.bin;D:\\Reactprojects\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;D:\\Reactprojects\\Weather\\client\\node_modules\\.bin;D:\\Reactprojects\\Weather\\node_modules\\.bin;D:\\Reactprojects\\node_modules\\.bin;D:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\siddh\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\siddh\\bin;C:\\Python311\\Scripts;C:\\Python311;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0;C:\\windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\siddh\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\siddh\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\siddh\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW",
  "PKG_CONFIG_PATH": "C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig",
  "PKG_CONFIG_SYSTEM_INCLUDE_PATH": "C:/Program Files/Git/mingw64/include",
  "PKG_CONFIG_SYSTEM_LIBRARY_PATH": "C:/Program Files/Git/mingw64/lib",
  "platformcode": "KV",
  "PLINK_PROTOCOL": "ssh",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD",
  "PROCESSOR_LEVEL": "23",
  "PROCESSOR_REVISION": "1801",
  "ProgramData": "C:\\ProgramData",
  "PROGRAMFILES": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PWD": "D:/Reactprojects/Weather/client",
  "RegionCode": "APJ",
  "SESSIONNAME": "Console",
  "SHELL": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "SHLVL": "2",
  "SSH_ASKPASS": "C:/Program Files/Git/mingw64/bin/git-askpass.exe",
  "SYSTEMDRIVE": "C:",
  "SYSTEMROOT": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\siddh\\AppData\\Local\\Temp",
  "TERM": "xterm-256color",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.81.1",
  "TMP": "C:\\Users\\siddh\\AppData\\Local\\Temp",
  "TMPDIR": "C:\\Users\\siddh\\AppData\\Local\\Temp",
  "USERDOMAIN": "MERO_PC",
  "USERDOMAIN_ROAMINGPROFILE": "MERO_PC",
  "USERNAME": "siddh",
  "USERPROFILE": "C:\\Users\\siddh",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\siddh\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\siddh\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-e80e92983b-sock",
  "WINDIR": "C:\\WINDOWS",
  "_": "C:/Program Files/nodejs/node.exe"
};